name: "Pipeline"
on:
  push:
    branches:
      - "staging"
jobs:
  ci:
    name: "CI CD Pipeline"
    runs-on: "ubuntu-latest"
    environment: staging
    env:
      DIST_FOLDER: ${{ vars.DIST_FOLDER }}
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_BUCKET_NAME: ${{ vars.GCP_BUCKET_NAME }}
    steps:
      - name: "Check env"
        run: |
          echo "DIST_FOLDER: $DIST_FOLDER"
          echo "GCP_PROJECT_ID: $GCP_PROJECT_ID"
          echo "GCP_BUCKET_NAME: $GCP_BUCKET_NAME"
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"

      - name: "Test gcloud CLI"
        run: "gcloud info"

      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: "moonrepo/setup-toolchain@v0"
      - run: "moon ci"
