name: "Pipeline"
on:
    push:
        branches:
            - "main"
jobs:
    ci:
        name: "CI"
        runs-on: "ubuntu-latest"
        steps:
            - name: Install uv
              run: pip install uv
            - uses: "actions/checkout@v4"
              with:
                  fetch-depth: 0
            - uses: "moonrepo/setup-toolchain@v0"
            - run: "moon ci"
