name: "Pipeline"
on:
  push:
    branches:
      - "staging"
jobs:
  ci:
    name: "CI CD Pipeline"
    runs-on: "ubuntu-latest"
    environment: staging
    env:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "moonrepo/setup-toolchain@v0"
      - run: "moon ci"
